fix: remove `slashValidator` gating on active status
Causing failures on deployment throwing with:

```
2026-06-26 05:53:29.875	
Error: InCorrectCurrentTargetUnslashedBalance
2026-06-26 05:53:29.875	
    at BeaconChain.verifyBlocksInEpoch (file:///usr/src/lodestar/packages/beacon-node/src/chain/blocks/verifyBlock.ts:176:7)
2026-06-26 05:53:29.875	
    at JobItemQueue.runJob (file:///usr/src/lodestar/packages/beacon-node/src/util/queue/itemQueue.ts:149:22)
2026-06-26 05:53:29.875	
    at NativeBeaconStateView.stateTransition (file:///usr/src/lodestar/packages/state-transition/src/stateView/nativeBeaconStateView.ts:661:54)
```

See: https://github.com/ChainSafe/lodestar/blob/848b01419b92832ea4d0d6b32595641e3cf5cd75/packages/state-transition/src/block/slashValidator.ts#L87-L95